version: "3"
services:
  jekyll_web:
    build: .
    container_name: local_jekyll
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    command: bundle exec jekyll serve --host=0.0.0.0
    ports:
      - "4000:4000"

volumes:
  bundle:
